# Generated by Django 6.0.6 on 2026-06-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='楼名')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('floors', models.IntegerField(default=6, verbose_name='楼层数')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宿舍楼',
                'verbose_name_plural': '宿舍楼',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='院系')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('enrollment_year', models.IntegerField(blank=True, null=True, verbose_name='入学年份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='房间号')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('capacity', models.IntegerField(verbose_name='容量')),
                ('current_count', models.IntegerField(default=0, verbose_name='当前人数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.building', verbose_name='所属楼栋')),
            ],
            options={
                'verbose_name': '宿舍房间',
                'verbose_name_plural': '宿舍房间',
                'ordering': ['building', 'room_number'],
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=50, verbose_name='报修人')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='报修日期')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('handler', models.CharField(blank=True, max_length=50, verbose_name='处理人')),
                ('handle_date', models.DateTimeField(blank=True, null=True, verbose_name='处理日期')),
                ('note', models.TextField(blank=True, verbose_name='处理备注')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory', verbose_name='宿舍')),
            ],
            options={
                'verbose_name': '报修',
                'verbose_name_plural': '报修',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(auto_now_add=True, verbose_name='入住日期')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='退宿日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory', verbose_name='宿舍')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '住宿分配',
                'verbose_name_plural': '住宿分配',
                'ordering': ['-check_in_date'],
            },
        ),
    ]
